/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  LocationSegments,
  MatchResults,
  RouterHistory,
} from '@stencil/router';

export namespace Components {
  interface RouterDemoApp {}
  interface TestDeepComponent {
    'history'?: RouterHistory;
    'location'?: LocationSegments;
  }
  interface TestDemoEight {}
  interface TestDemoFour {
    'history'?: RouterHistory;
    'match': MatchResults | null;
    'pages': string[];
  }
  interface TestDemoSeven {
    'history'?: RouterHistory;
    'match'?: MatchResults;
    'pages'?: string[];
  }
  interface TestDemoSix {
    'history'?: RouterHistory;
    'match': MatchResults | null;
    'pages'?: string[];
  }
  interface TestDemoThree {
    'history'?: RouterHistory;
    'match': MatchResults | null;
    'pages'?: string[];
  }
  interface TestRouteGuard {
    'history'?: RouterHistory;
    'match': MatchResults | null;
    'pages'?: string[];
  }
}

declare global {


  interface HTMLRouterDemoAppElement extends Components.RouterDemoApp, HTMLStencilElement {}
  const HTMLRouterDemoAppElement: {
    prototype: HTMLRouterDemoAppElement;
    new (): HTMLRouterDemoAppElement;
  };

  interface HTMLTestDeepComponentElement extends Components.TestDeepComponent, HTMLStencilElement {}
  const HTMLTestDeepComponentElement: {
    prototype: HTMLTestDeepComponentElement;
    new (): HTMLTestDeepComponentElement;
  };

  interface HTMLTestDemoEightElement extends Components.TestDemoEight, HTMLStencilElement {}
  const HTMLTestDemoEightElement: {
    prototype: HTMLTestDemoEightElement;
    new (): HTMLTestDemoEightElement;
  };

  interface HTMLTestDemoFourElement extends Components.TestDemoFour, HTMLStencilElement {}
  const HTMLTestDemoFourElement: {
    prototype: HTMLTestDemoFourElement;
    new (): HTMLTestDemoFourElement;
  };

  interface HTMLTestDemoSevenElement extends Components.TestDemoSeven, HTMLStencilElement {}
  const HTMLTestDemoSevenElement: {
    prototype: HTMLTestDemoSevenElement;
    new (): HTMLTestDemoSevenElement;
  };

  interface HTMLTestDemoSixElement extends Components.TestDemoSix, HTMLStencilElement {}
  const HTMLTestDemoSixElement: {
    prototype: HTMLTestDemoSixElement;
    new (): HTMLTestDemoSixElement;
  };

  interface HTMLTestDemoThreeElement extends Components.TestDemoThree, HTMLStencilElement {}
  const HTMLTestDemoThreeElement: {
    prototype: HTMLTestDemoThreeElement;
    new (): HTMLTestDemoThreeElement;
  };

  interface HTMLTestRouteGuardElement extends Components.TestRouteGuard, HTMLStencilElement {}
  const HTMLTestRouteGuardElement: {
    prototype: HTMLTestRouteGuardElement;
    new (): HTMLTestRouteGuardElement;
  };
  interface HTMLElementTagNameMap {
    'router-demo-app': HTMLRouterDemoAppElement;
    'test-deep-component': HTMLTestDeepComponentElement;
    'test-demo-eight': HTMLTestDemoEightElement;
    'test-demo-four': HTMLTestDemoFourElement;
    'test-demo-seven': HTMLTestDemoSevenElement;
    'test-demo-six': HTMLTestDemoSixElement;
    'test-demo-three': HTMLTestDemoThreeElement;
    'test-route-guard': HTMLTestRouteGuardElement;
  }
}

declare namespace LocalJSX {
  interface RouterDemoApp {}
  interface TestDeepComponent {
    'history'?: RouterHistory;
    'location'?: LocationSegments;
  }
  interface TestDemoEight {}
  interface TestDemoFour {
    'history'?: RouterHistory;
    'match'?: MatchResults | null;
    'pages'?: string[];
  }
  interface TestDemoSeven {
    'history'?: RouterHistory;
    'match'?: MatchResults;
    'pages'?: string[];
  }
  interface TestDemoSix {
    'history'?: RouterHistory;
    'match'?: MatchResults | null;
    'pages'?: string[];
  }
  interface TestDemoThree {
    'history'?: RouterHistory;
    'match'?: MatchResults | null;
    'pages'?: string[];
  }
  interface TestRouteGuard {
    'history'?: RouterHistory;
    'match'?: MatchResults | null;
    'pages'?: string[];
  }

  interface IntrinsicElements {
    'router-demo-app': RouterDemoApp;
    'test-deep-component': TestDeepComponent;
    'test-demo-eight': TestDemoEight;
    'test-demo-four': TestDemoFour;
    'test-demo-seven': TestDemoSeven;
    'test-demo-six': TestDemoSix;
    'test-demo-three': TestDemoThree;
    'test-route-guard': TestRouteGuard;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'router-demo-app': LocalJSX.RouterDemoApp & JSXBase.HTMLAttributes<HTMLRouterDemoAppElement>;
      'test-deep-component': LocalJSX.TestDeepComponent & JSXBase.HTMLAttributes<HTMLTestDeepComponentElement>;
      'test-demo-eight': LocalJSX.TestDemoEight & JSXBase.HTMLAttributes<HTMLTestDemoEightElement>;
      'test-demo-four': LocalJSX.TestDemoFour & JSXBase.HTMLAttributes<HTMLTestDemoFourElement>;
      'test-demo-seven': LocalJSX.TestDemoSeven & JSXBase.HTMLAttributes<HTMLTestDemoSevenElement>;
      'test-demo-six': LocalJSX.TestDemoSix & JSXBase.HTMLAttributes<HTMLTestDemoSixElement>;
      'test-demo-three': LocalJSX.TestDemoThree & JSXBase.HTMLAttributes<HTMLTestDemoThreeElement>;
      'test-route-guard': LocalJSX.TestRouteGuard & JSXBase.HTMLAttributes<HTMLTestRouteGuardElement>;
    }
  }
}


