/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  LocationSegments,
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface RouterDemoApp {}
  interface RouterDemoAppAttributes extends StencilHTMLAttributes {}

  interface TestDeepComponent {
    'history': RouterHistory;
    'location': LocationSegments;
  }
  interface TestDeepComponentAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'location'?: LocationSegments;
  }

  interface TestDemoFour {
    'history': RouterHistory;
    'match': MatchResults;
    'pages': string[];
  }
  interface TestDemoFourAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
    'pages'?: string[];
  }

  interface TestDemoSeven {
    'history': RouterHistory;
    'match': MatchResults;
    'pages': string[];
  }
  interface TestDemoSevenAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
    'pages'?: string[];
  }

  interface TestDemoSix {
    'history': RouterHistory;
    'match': MatchResults;
    'pages': string[];
  }
  interface TestDemoSixAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
    'pages'?: string[];
  }

  interface TestDemoThree {
    'history': RouterHistory;
    'match': MatchResults;
    'pages': string[];
  }
  interface TestDemoThreeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
    'pages'?: string[];
  }
}

declare global {
  interface StencilElementInterfaces {
    'RouterDemoApp': Components.RouterDemoApp;
    'TestDeepComponent': Components.TestDeepComponent;
    'TestDemoFour': Components.TestDemoFour;
    'TestDemoSeven': Components.TestDemoSeven;
    'TestDemoSix': Components.TestDemoSix;
    'TestDemoThree': Components.TestDemoThree;
  }

  interface StencilIntrinsicElements {
    'router-demo-app': Components.RouterDemoAppAttributes;
    'test-deep-component': Components.TestDeepComponentAttributes;
    'test-demo-four': Components.TestDemoFourAttributes;
    'test-demo-seven': Components.TestDemoSevenAttributes;
    'test-demo-six': Components.TestDemoSixAttributes;
    'test-demo-three': Components.TestDemoThreeAttributes;
  }


  interface HTMLRouterDemoAppElement extends Components.RouterDemoApp, HTMLStencilElement {}
  var HTMLRouterDemoAppElement: {
    prototype: HTMLRouterDemoAppElement;
    new (): HTMLRouterDemoAppElement;
  };

  interface HTMLTestDeepComponentElement extends Components.TestDeepComponent, HTMLStencilElement {}
  var HTMLTestDeepComponentElement: {
    prototype: HTMLTestDeepComponentElement;
    new (): HTMLTestDeepComponentElement;
  };

  interface HTMLTestDemoFourElement extends Components.TestDemoFour, HTMLStencilElement {}
  var HTMLTestDemoFourElement: {
    prototype: HTMLTestDemoFourElement;
    new (): HTMLTestDemoFourElement;
  };

  interface HTMLTestDemoSevenElement extends Components.TestDemoSeven, HTMLStencilElement {}
  var HTMLTestDemoSevenElement: {
    prototype: HTMLTestDemoSevenElement;
    new (): HTMLTestDemoSevenElement;
  };

  interface HTMLTestDemoSixElement extends Components.TestDemoSix, HTMLStencilElement {}
  var HTMLTestDemoSixElement: {
    prototype: HTMLTestDemoSixElement;
    new (): HTMLTestDemoSixElement;
  };

  interface HTMLTestDemoThreeElement extends Components.TestDemoThree, HTMLStencilElement {}
  var HTMLTestDemoThreeElement: {
    prototype: HTMLTestDemoThreeElement;
    new (): HTMLTestDemoThreeElement;
  };

  interface HTMLElementTagNameMap {
    'router-demo-app': HTMLRouterDemoAppElement
    'test-deep-component': HTMLTestDeepComponentElement
    'test-demo-four': HTMLTestDemoFourElement
    'test-demo-seven': HTMLTestDemoSevenElement
    'test-demo-six': HTMLTestDemoSixElement
    'test-demo-three': HTMLTestDemoThreeElement
  }

  interface ElementTagNameMap {
    'router-demo-app': HTMLRouterDemoAppElement;
    'test-deep-component': HTMLTestDeepComponentElement;
    'test-demo-four': HTMLTestDemoFourElement;
    'test-demo-seven': HTMLTestDemoSevenElement;
    'test-demo-six': HTMLTestDemoSixElement;
    'test-demo-three': HTMLTestDemoThreeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
