/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import { JSXElements } from '@stencil/core';

import { LocalIntrinsicElements as DependentIntrinsicElements1 } from '@stencil/router';
import {
  LocationSegments,
  MatchResults,
  RouterHistory,
} from '@stencil/router';


declare namespace StencilComponents {

  interface RouterDemoApp {}
  interface RouterDemoAppAttributes extends JSXElements.HTMLAttributes {}

  interface TestDeepComponent {
    'history': RouterHistory;
    'location': LocationSegments;
  }
  interface TestDeepComponentAttributes extends JSXElements.HTMLAttributes {
    'history'?: RouterHistory;
    'location'?: LocationSegments;
  }

  interface TestDemoFour {
    'history': RouterHistory;
    'match': MatchResults;
    'pages': string[];
  }
  interface TestDemoFourAttributes extends JSXElements.HTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
    'pages'?: string[];
  }

  interface TestDemoSeven {
    'history': RouterHistory;
    'match': MatchResults;
    'pages': string[];
  }
  interface TestDemoSevenAttributes extends JSXElements.HTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
    'pages'?: string[];
  }

  interface TestDemoSix {
    'history': RouterHistory;
    'match': MatchResults;
    'pages': string[];
  }
  interface TestDemoSixAttributes extends JSXElements.HTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
    'pages'?: string[];
  }

  interface TestDemoThree {
    'history': RouterHistory;
    'match': MatchResults;
    'pages': string[];
  }
  interface TestDemoThreeAttributes extends JSXElements.HTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
    'pages'?: string[];
  }
}

export interface LocalIntrinsicElements {
  'router-demo-app': StencilComponents.RouterDemoAppAttributes;
  'test-deep-component': StencilComponents.TestDeepComponentAttributes;
  'test-demo-four': StencilComponents.TestDemoFourAttributes;
  'test-demo-seven': StencilComponents.TestDemoSevenAttributes;
  'test-demo-six': StencilComponents.TestDemoSixAttributes;
  'test-demo-three': StencilComponents.TestDemoThreeAttributes;
}

declare global {

  interface HTMLRouterDemoAppElement extends StencilComponents.RouterDemoApp, HTMLStencilElement {}
  var HTMLRouterDemoAppElement: {
    prototype: HTMLRouterDemoAppElement;
    new (): HTMLRouterDemoAppElement;
  };

  interface HTMLTestDeepComponentElement extends StencilComponents.TestDeepComponent, HTMLStencilElement {}
  var HTMLTestDeepComponentElement: {
    prototype: HTMLTestDeepComponentElement;
    new (): HTMLTestDeepComponentElement;
  };

  interface HTMLTestDemoFourElement extends StencilComponents.TestDemoFour, HTMLStencilElement {}
  var HTMLTestDemoFourElement: {
    prototype: HTMLTestDemoFourElement;
    new (): HTMLTestDemoFourElement;
  };

  interface HTMLTestDemoSevenElement extends StencilComponents.TestDemoSeven, HTMLStencilElement {}
  var HTMLTestDemoSevenElement: {
    prototype: HTMLTestDemoSevenElement;
    new (): HTMLTestDemoSevenElement;
  };

  interface HTMLTestDemoSixElement extends StencilComponents.TestDemoSix, HTMLStencilElement {}
  var HTMLTestDemoSixElement: {
    prototype: HTMLTestDemoSixElement;
    new (): HTMLTestDemoSixElement;
  };

  interface HTMLTestDemoThreeElement extends StencilComponents.TestDemoThree, HTMLStencilElement {}
  var HTMLTestDemoThreeElement: {
    prototype: HTMLTestDemoThreeElement;
    new (): HTMLTestDemoThreeElement;
  };

  interface HTMLElementTagNameMap {
    'router-demo-app': HTMLRouterDemoAppElement
    'test-deep-component': HTMLTestDeepComponentElement
    'test-demo-four': HTMLTestDemoFourElement
    'test-demo-seven': HTMLTestDemoSevenElement
    'test-demo-six': HTMLTestDemoSixElement
    'test-demo-three': HTMLTestDemoThreeElement
  }

  interface ElementTagNameMap {
    'router-demo-app': HTMLRouterDemoAppElement;
    'test-deep-component': HTMLTestDeepComponentElement;
    'test-demo-four': HTMLTestDemoFourElement;
    'test-demo-seven': HTMLTestDemoSevenElement;
    'test-demo-six': HTMLTestDemoSixElement;
    'test-demo-three': HTMLTestDemoThreeElement;
  }
}


import { DefaultIntrinsicElements } from '@stencil/core';

declare global {
  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends LocalIntrinsicElements, DefaultIntrinsicElements, DependentIntrinsicElements1 {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends JSXElements.HTMLAttributes {}
}

